apiVersion: v1
kind: PersistentVolume
metadata:
  name: masktv-app-pv
  labels:
    app: masktv-app
spec:
  storageClassName: ""
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/efs/app/app-file  # Path on all nodes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-20-250.ap-south-1.compute.internal
