
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: masktv-app-hpa
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: masktv-app-deployment
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
