apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
# download app file from s3
  AWS_ACCESS_KEY_ID: QUtJQVRNRFNNSk9RU1pMWDNNWEw=
  AWS_SECRET_ACCESS_KEY: eFFrWWhBbEQ4LzdEam1zY21hWkdRYkFRZS9wbytZN2pLR0FCVmhjKw==
