apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: masktv-mysql-statefulset
  labels:
    app: masktv-mysql
spec:
  serviceName: "masktv-mysql-service"
  replicas: 5
  selector:
    matchLabels:
      app: masktv-mysql
  template:
    metadata:
      labels:
        app: masktv-mysql
    spec:
      containers:
      - name:  masktv-mysql-statefulset
        image: .....................
        ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
        resources: 
          requests: 
            cpu: 200m
            memory: 100Mi
        env:
          #- name: MYSQL_ROOT_PASSWORD
            #valueFrom:
              #secretKeyRef:
                #name: database-secrets
                #key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MYSQL_PASSWORD
        volumeMounts:
        - name: masktv-mysql-pv
          mountPath: /var/lib/mysql
        - name: db-log-pv
          mountPath: /var/log/mysql
      volumes:
      - name: db-log-pv
        persistentVolumeClaim:
          claimName: db-log-pvc
      - name: masktv-mysql-pv
        persistentVolumeClaim:
          claimName: masktv-mysql-pvc
