
apiVersion: v1
kind: PersistentVolume
metadata:
  name: masktv-mysql-pv-2  # Third PV for the third replica
  labels:
    app: masktv-mysql
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/efs/db-2  # Ensure this directory exists on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - ip-10-0-2-166.ap-south-1.compute.internal
