apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  provisioner: efs.csi.aws.com
  fileSystemId: fs-06e6beca57541633b
# Replace with your actual EFS ID
  # Optional parameters
  # Directory: This is the path in EFS where volumes will be created.
  directory: /mnt/test # Optional, defaults to root if not specified
