apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs  # Change to your desired provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: gp2  
  fsType: ext4      
