apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: masktv-mysql-statefulset
  labels:
    app: masktv-mysql
spec:
  serviceName: "masktv-mysql-service"
  replicas: 3
  selector:
    matchLabels:
      app: masktv-mysql
  template:
    metadata:
      labels:
        app: masktv-mysql
    spec:
      containers:
        - name: masktv-mysql-container
          image: masktv/masktv:sql
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: masktv-mysql-pvc-0  # For the first pod
              mountPath: /var/lib/mysql
            - name: masktv-mysql-pvc-1  # For the second pod
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MYSQL_PASSWORD
      volumes:
        - name: masktv-mysql-pvc-0
          persistentVolumeClaim:
            claimName: masktv-mysql-pvc-0  # Reference to the existing PVC
        - name: masktv-mysql-pvc-1
          persistentVolumeClaim:
            claimName: masktv-mysql-pvc-1  # Reference to the existing PVC
        - name: masktv-mysql-pvc-2
          persistentVolumeClaim:
            claimName: masktv-mysql-pvc-2            
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0  # State can be managed by partitioning.

